### ISSUE TITLE
Problematic use In Qt code

### ISSUE THREAD

**Issue by jcelerier** [NoAvailableAlias/nano-signal-slot#12]
The `Signal::emit` function clashes with Qt's `#define emit` and causes tons of compilation error :-( For now I renamed it into `operator()` in my code, should I just keep my fork ?

**Comment by NoAvailableAlias** [comment]
There isn't a solution other than to rename Signal::emit whenever offensively defined macros are involved. Might consider renaming in the future but for now you'll have to use your fork.

**Comment by isgursoy** [comment]
@jcelerier  You can disable (all or) only emit keyword of Qt by passing relevant CONFIG switch.

**Comment by jcelerier** [comment]
right, but when you have a few hundred thousand lines of Qt code, it's kinda painful to replace signal by Q_SIGNAL everywhere

**Comment by isgursoy** [comment]
What is wrong with the search & replace of Qt Creator?

**Comment by jcelerier** [comment]
it takes hours to double-check that every "signal" is indeed a Qt keyword and not an unrelated variable in some C header for instance

**Comment by isgursoy** [comment]
Should not `signal:` pattern be unique?

**Comment by jcelerier** [comment]
not in my experience, it can be in string literals, comments, etc

**Comment by jcelerier** [comment]
e.g. I just checked in my $HOME for 

     rg '\ssignals:'  -g '*.{h,hpp}'

and the instances we want to match are a fraction of the occurences I'm seeing there

**Comment by isgursoy** [comment]
> e.g. I just checked in my $HOME for
> 
> ```
>  rg '\ssignals:'  -g '*.{h,hpp}'
> ```
> 
> and the instances we want to match are a fraction of the occurences I'm seeing there

There is almost always newline at the beginning (no any thing before `signal`) and probably there is almost always newline at the end. Also signal function signatures are always returning void so you have another tip here.
Look for:
```
|--probably-newline--|
signals:|--probably-newline--|
|--probably-some-whitespace--|void
```

If you have such a comment, replace it too. If you have such an exact string literal, bad luck.
