### ISSUE TITLE
How to remove all Slots from a Signal?

### ISSUE THREAD

**Issue by offa** [NoAvailableAlias/nano-signal-slot#14]
Is there a way to remove all connected slots from a Signal?

**Comment by NoAvailableAlias** [comment]
A "removeAll" type method would need to be created for Nano::Observer that walks and deletes all nodes from the list. In the same process any Observers that aren't "this" would need to remove "this". I'm currently trying to gather time and evaluate planned changes for the first release, but for now I'll leave this issue open and get a "removeAll" method added.

**Comment by NoAvailableAlias** [comment]
A "removeAll" method has been added.

**Comment by offa** [comment]
Perfect, thanks! :+1:
