### ISSUE TITLE
virtual dtor in Nano::Observer?

### ISSUE THREAD

**Issue by offa** [NoAvailableAlias/nano-signal-slot#19]
The dtor of `Nano::Observer` is not virtual – shouldn't it be virtual?

Enabling `Weffc++` for classes which inherit from `Observer` emit following warning (Gcc6):

```
error: base class ‘class Nano::Observer’ has accessible non-virtual destructor [-Werror=non-virtual-dtor]
```

**Comment by NoAvailableAlias** [comment]
Nano::Observer destructor should not be accessible due to being protected. I believe that alone is enough.
