### ISSUE TITLE
how to get return value?

### ISSUE THREAD

**Issue by xzwang2005** [NoAvailableAlias/nano-signal-slot#20]
The sample code didn't show how to retrieve the return value.  What's the syntax for that?

**Comment by NoAvailableAlias** [comment]
Hello, in order to access signal return values you must use the syntax shown here: [emit_accumulate](https://github.com/NoAvailableAlias/nano-signal-slot#emit--emit-accumulate). You have to use the emit_accumulate method and pass a lambda in order to access the return values.

**Comment by xzwang2005** [comment]
Thanks.
