### ISSUE TITLE
Library is not thread-safe: deadlock can happen 

### ISSUE THREAD

**Issue by sergey-shambir** [NoAvailableAlias/nano-signal-slot#22]
Here library calls foreign callbacks under mutex lock:

```cpp
template <typename Function, typename... Uref>
    void for_each(Uref&&... args)
    {
        std::unique_lock<Mutex> lock(mutex);

        auto iter = connections.cbegin();
        auto stop = connections.cend();

        while (iter != stop)
        {
            auto const& delegate = (*iter)->first;
            std::advance(iter, 1);

            // Perfect forward and fire
            Function::bind(delegate)(std::forward<Uref>(args)...);
        }
}
```

Imagine that one thread connects to "signal1" own function "slot1" which fires "signal2". First, it locks "signal1" mutex, then attempts to lock "signal2" mutex.

Another thread connects to "signal2" own function "slot2" which fires "signal1". First, it locks "signal2" mutex, then attempts to lock "signal1" mutex.

In some cases, threads will enter into deadlock: thread1 always waits "signal2" mutex, while thread2 always waits "signal1" mutex.

Illustration:
![default](https://user-images.githubusercontent.com/1856842/44581044-ef88df80-a7a4-11e8-9cce-926235e3faa8.png)

**Comment by NoAvailableAlias** [comment]
Thank you for creating this issue as well as the detailed explanation. Not sure I see an immediate no cost solution to this with the current iteration of Nano::Observer. 

In the meantime I will add a readme section concerning recursive signal operations / dependencies and this likely deadlock scenario.

**Comment by NoAvailableAlias** [comment]
Also spin mutex isn't entirely applicable in this implementation due to the unknown amount of time signal emission could take. Will try to find time.

**Comment by NoAvailableAlias** [comment]
Well just remembered why I had a lingering doubt about commenting as fixed...

The TS_Policy_Strict needs to unlock after copying the slot vector or else this issue isn't fixed.

Also decided to keep spin lock as the default but can be reconfigured through the policy.

Basically goal is to allow for "fast with gotchas" or "slow and safe" through the use of these policies.

**Comment by NoAvailableAlias** [comment]
Status Update:

There is a [data race](https://github.com/NoAvailableAlias/nano-signal-slot/blob/rework/nano_observer.hpp#L98) issue that "could" be encountered depending on the usage of the TS_Policy_Strict policy for nano-signal-slot/rework.

It should be possible to prove there is no race if the program can guarantee to never perform an emission on slots that are already destructed. (would require signal vs slot lifetime analysis as well as analysis of the overall threading architecture in regards to signal emission)

I would ultimately like to resolve this with yet another policy, but I am sure it would not be trivial.

**Comment by sergey-shambir** [comment]
I suggest to describe in README.md how to use MT_Policy policies.
From my point of view, README must inform users how to use this library for maximum performance and for complete thread safety (and I'm not fun of semi-safe policies where multithreaded emitting is safe, but emitting from slot isn't).

Since policies are template params, it's better for any users to create alias header where nano-signal-slot signals will be aliased and configured with `using`, e.g.:

```cpp
#include <nano-signal-slot/nano_signal_slot.hpp>

namespace MyNamespace
{
template <typename Signature>
using Signal<Signature> = Nano::Signal<Signature, Nano::TS_Policy_Strict>

// ... other aliases
}
```

We used similar header file for Boost.Signals2 and easily switched to another signal/slot library by changing this header and a few other places (where weird code accepted by Boost but caused compiler error with another lib).

**Comment by NoAvailableAlias** [comment]
Thanks for the suggestion, a new Policies section will be added to the readme.

Also, the TS_Policy_Strict will be renamed to TS_Policy_Safe and will contain the mitigations against both the deadlock and this data race.

Will probably be a bit due to all policies requiring changes (in order to achieve pay for what you use).
