### ISSUE TITLE
gcc 5.4 cannot permitted auto

### ISSUE THREAD

**Issue by aitazhixin** [NoAvailableAlias/nano-signal-slot#23]
template<auto mem_ptr>
...
cannot be permitted by c++17 in gcc.

**Comment by NoAvailableAlias** [comment]
There is hardly any c++17 support in gcc 5.4 [compared to either 6 or 7.x](https://gcc.gnu.org/projects/cxx-status.html#cxx1z)

A gcc version >= 7 should have enough c++17 support although my testing was on 8.1 so ymmv
